# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BeLin 6.0 kiadás - kezdőlap
email: hammer.attila@infoalap.hu
description: > # this means to ignore newlines until "baseurl:"
  A BeLin 6.0 kiadás egy látássérült felhasználók számára képernyőolvasó és nagyító szoftverrel használható Ubuntu alapú speciális Linux disztribúció.
baseurl: "/documentation" # the subpath of your site, e.g. /blog
url: "https://belin-ubuntu.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  belin-ubuntu

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
